### ISSUE TITLE
Package not found PX4_Controller, Image_Pub, Caffe_ROS

### ISSUE THREAD

**Issue by amano001** [NVIDIA-AI-IOT/redtail#105]
I followed the Wiki pretty closely, I am able to get gazbeo running with QGround Control linked in.  I did use the nvidia docker image but when I try to run the controller node, image and caffe it says package not found for any of them.  I see the folders (although they are showing archived red?)  for each of those packages inside the ws in docker.

**Comment by Alexey-Kamenev** [comment]
Our Docker build script [creates](../blob/master/tools/simulation/docker/Dockerfile.kinetic#L179) symbolic links to redtail source code rather than pulling the sources directly into the container. Please check the target for those symlinks and make sure they point to the right place (i.e. redtail source code directory).

**Comment by amano001** [comment]
Thanks Alexey,

I will try checking the symlinks to make sure they are pointing to the right spot.

**Comment by amano001** [comment]
Hey Alexey,

Just wanted to say thanks that did the trick, I was not pointing at the correct directories.
